name: Market Report

on:
  workflow_dispatch:

  schedule:
    - cron: "0 23 * * *"

permissions:
  contents: write

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Show files
        run: |
          pwd
          ls -lah

      - name: Install dependencies
        run: |
          python -V
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python -u coin_stock_report_g_20260712_001.py

      - name: Commit Excel
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          if [ -f market_data_greport.xlsx ]; then
            git add market_data_greport.xlsx
            git diff --cached --quiet || git commit -m "Automatic market update"
            git push
          else
            echo "Excel file not found."
          fi
