name: Market Report

on:
  schedule:
    - cron: "0 23 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python market_data.py

      - name: Commit Excel file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add market_data_greport.xlsx

          git diff --cached --quiet || git commit -m "Automatic market update"

          git push
